### ISSUE TITLE
After upgrading to the latest PIO (v6.0.1), the build of ament packages (ament_lint, ament_cppcheck) seems to fail with an AttributeError ('install_layout')

### ISSUE THREAD

**Issue by alikureishy** [micro-ROS/micro_ros_platformio#31]
## Issue template

- Hardware description: Ubuntu 20.04, ESP32
- RTOS: arduino
- Installation type: pio lib install; pio run
- Version or commit hash: main

#### Steps to reproduce the issue

Step 1: Upgrade system to the latest PIO version:
```
> pio upgrade
```

Step 2: Copy the contents of the micro_ros_publisher example.

Step 3: Other tool versions:
- Espressif: v4.3
- Python: 3.8.0
- ROS: galactic

Step 4: With the following platformio.ini (mostly unchanged from the example, except for the addition of platform/board properties):
```
[env]
monitor_speed = 115200
upload_speed = 921600

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_microros_transport = serial
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
```

Run:
```
> pio run --target clean_microros
> pio lib install
> pio run
```

#### Expected behavior

```pio run``` should build the packages successfully.

#### Actual behavior

Build fails with the following output:
```
Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (4.3.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20003.0 (2.0.3) 
 - tool-esptoolpy @ 1.30300.0 (3.3.0) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Installing pyyaml with pip at PlatformIO environment
/home/safdar/.platformio/penv/bin/python -m pip install pyyaml
Requirement already satisfied: pyyaml in /home/safdar/.platformio/penv/lib/python3.8/site-packages (6.0)
Installing markupsafe==2.0.1 with pip at PlatformIO environment
/home/safdar/.platformio/penv/bin/python -m pip install markupsafe==2.0.1
Requirement already satisfied: markupsafe==2.0.1 in /home/safdar/.platformio/penv/lib/python3.8/site-packages (2.0.1)
Configuring esp32dev with transport wifi
Downloading micro-ROS dev dependencies
         - Downloaded ament_cmake
         - Downloaded ament_lint
         - Downloaded ament_package
         - Downloaded googletest
         - Downloaded ament_cmake_ros
         - Downloaded ament_index
Building micro-ROS dev dependencies
Build dev micro-ROS environment failed: 
 --- stderr: gtest_vendor
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING


---
--- stderr: gmock_vendor
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING


---
--- stderr: ament_lint
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    setup(
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/command/develop.py", line 56, in finalize_options
    easy_install.finalize_options(self)
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
    self.set_undefined_options(
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 287, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 290, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout
---
Failed   <<< ament_lint [1.50s, exited with code 1]
```

This could also return an error for a different ament package, like ament_cppcheck.

#### Additional information

As far as I remember, the only change I made since a previous successful compilation is that I upgraded platformio to version 6.0. I can't think of any other system change that I've made, since the last time this successfully compiled.

**Comment by pablogs9** [comment]
Please recheck, I have just built an example with v6.0.1 and no error found: https://asciinema.org/a/CUabJzSrulHxxCUkIDGJmDYk3

**Comment by pablogs9** [comment]
Any update on this?

**Comment by alikureishy** [comment]
I tried the following, but still keep getting that error:

**pio platform update**
```
Platform espressif32
--------
Platform Manager: Updating espressif32 @ 4.3.0
Platform Manager: Removing espressif32 @ 4.3.0
Platform Manager: espressif32@4.3.0 has been removed!
Platform Manager: Installing platformio/espressif32 @ 4.4.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Platform Manager: espressif32@4.4.0 has been installed!
Tool Manager: toolchain-xtensa-esp32@8.4.0+2021r2-patch3 is already installed
Tool Manager: tool-esptoolpy@1.30300.0 is already installed
Tool Manager: Updating framework-arduinoespressif32 @ 3.20003.0
Tool Manager: Removing framework-arduinoespressif32 @ 3.20003.0
Tool Manager: framework-arduinoespressif32@3.20003.0 has been removed!
Tool Manager: Installing platformio/framework-arduinoespressif32 @ 3.20003.220619
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: framework-arduinoespressif32@3.20003.220619 has been installed!
Tool Manager: framework-espidf@3.40302.0 is already up-to-date
Tool Manager: tool-cmake@3.16.4 is already up-to-date
Tool Manager: tool-esptoolpy@1.30300.0 is already up-to-date
Tool Manager: tool-mkfatfs@2.0.1 is already up-to-date
Tool Manager: tool-mklittlefs@1.203.210628 is already up-to-date
Tool Manager: tool-mkspiffs@2.230.0 is already up-to-date
Tool Manager: tool-ninja@1.7.1 is already up-to-date
Tool Manager: toolchain-esp32ulp@1.22851.191205 is already up-to-date
Tool Manager: toolchain-riscv32-esp@8.4.0+2021r2-patch3 is already up-to-date
Tool Manager: toolchain-xtensa-esp32@8.4.0+2021r2-patch3 is already up-to-date
Tool Manager: toolchain-xtensa-esp32s2@8.4.0+2021r2-patch3 is already up-to-date

Platform espressif32
--------
Platform Manager: espressif32@3.3.1+sha.3784198 is already up-to-date
Tool Manager: tool-cmake@3.16.4 is already up-to-date
Tool Manager: tool-esptoolpy@1.30100.210531 is already up-to-date
Tool Manager: tool-mkspiffs@2.230.0 is already up-to-date
Tool Manager: tool-ninja@1.7.1 is already up-to-date
Tool Manager: toolchain-esp32ulp@1.22851.191205 is already up-to-date
Tool Manager: toolchain-xtensa32@2.80400.210211 is already up-to-date
```

**pio lib update**
```
Library Storage: /home/safdar/code/repositories/cognitum/7_simulators/realworld/microros/bashi_sim_realworld_microros_firmware/.archive/arduino/micro_ros_platformio/esp32/.pio/libdeps/pio_arduino_microros_esp32dev_wifi
Library Manager: micro_ros_platformio@0.0.1+sha.285dd94 is already up-to-date
```

**pip install -U setuptools**
```
Requirement already satisfied: setuptools in /home/safdar/anaconda3/envs/ros2/lib/python3.8/site-packages (58.0.4)
Collecting setuptools
  Downloading setuptools-62.6.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 1.1 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.0.4
    Uninstalling setuptools-58.0.4:
      Successfully uninstalled setuptools-58.0.4
Successfully installed setuptools-62.6.0
```

**But still, after invoking the pio run -e <env_name>, I get:**
```
Processing pio_arduino_microros_esp32dev_wifi (platform: espressif32; framework: arduino; board: esp32dev)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (4.4.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20003.220619 (2.0.3) 
 - tool-esptoolpy @ 1.30300.0 (3.3.0) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Installing pyyaml with pip at PlatformIO environment
/home/safdar/.platformio/penv/bin/python -m pip install pyyaml
Requirement already satisfied: pyyaml in /home/safdar/.platformio/penv/lib/python3.8/site-packages (6.0)
WARNING: There was an error checking the latest version of pip.
Installing markupsafe==2.0.1 with pip at PlatformIO environment
/home/safdar/.platformio/penv/bin/python -m pip install markupsafe==2.0.1
Requirement already satisfied: markupsafe==2.0.1 in /home/safdar/.platformio/penv/lib/python3.8/site-packages (2.0.1)
WARNING: There was an error checking the latest version of pip.
Configuring esp32dev with transport wifi
Downloading micro-ROS dev dependencies
         - Downloaded ament_cmake
         - Downloaded ament_lint
         - Downloaded ament_package
         - Downloaded googletest
         - Downloaded ament_cmake_ros
         - Downloaded ament_index
Building micro-ROS dev dependencies
Build dev micro-ROS environment failed: 
 --- stderr: ament_cppcheck
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    setup(
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/command/develop.py", line 56, in finalize_options
    easy_install.finalize_options(self)
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
    self.set_undefined_options(
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 287, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 290, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout
---
Failed   <<< ament_cppcheck [1.37s, exited with code 1]
--- stderr: ament_package
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    setup(
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/command/develop.py", line 56, in finalize_options
    easy_install.finalize_options(self)
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
    self.set_undefined_options(
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 287, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/safdar/.platformio/penv/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 290, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
  File "/home/safdar/anaconda3/envs/ros2/lib/python3.8/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout
---
Failed   <<< ament_package [1.41s, exited with code 1]
```

**Comment by pablogs9** [comment]
Please try in a clean environment and report

**Comment by Acuadros95** [comment]
Any updates on this?

**Comment by Acuadros95** [comment]
Closing due to inactivity
